apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        ampersand.target: phptools.deployment
    name: phptools
    #namespace: ampersand-rap
spec:
    selector:
        matchLabels:
            ampersand.target: phptools.pod
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                ampersand.target: phptools.pod
        spec:
            hostname: phptools
            containers:
            - image: phpmyadmin/phpmyadmin
              name: phptools        
              ports:     
              - containerPort : 8080        
            restartPolicy: Always            
status: {}