apiVersion: v1
kind: PersistentVolume
metadata:
    name: rap-db-data
    namespace: prod
    labels:
        ampersand.target: rap.db.data.pv
spec:
    storageClassName: hostpath
    capacity:
        storage: 200Mi        
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/Users/mwa17610/volumes/k8s/rap/db/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        ampersand.target: rap.db.pvc
    name: rap-db-data
    namespace: prod
spec:
    storageClassName: hostpath
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Mi
status: {}   