apiVersion: v1
kind: Namespace
metadata: 
  name: prod
---
apiVersion: v1
kind: Service
metadata:
    #ampersand database is hardcode in image to db
    name: db
    #name: rap-db-service
    namespace: prod
    labels : 
        ampersand.target: rap.db.service
spec:
    type: NodePort
    ports:
    - name: "rap-db-port"
      port: 3306
      targetPort: 3306
      nodePort: 31100
    selector:
        ampersand.target: rap.db.pod
status: 
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        ampersand.target: rap.db.deployment
    name: rap-db
    namespace: prod
spec:
    selector:
        matchLabels:
            ampersand.target: rap.db.pod
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                ampersand.target: rap.db.pod
        spec:
            hostname: rap-db
            containers:
            - image: ampersandtarski/rap4-db
              name: rap-db
              volumeMounts:
              - mountPath: /var/lib/mysql
                name: rap-db-data
              ports:
              - containerPort : 80        
            restartPolicy: Always
            volumes:
            - name: rap-db-data
              azureFile:
                secretName: storage-secret
                shareName: /var/lib/mysql
                readOnly: false
                #persistentVolumeClaim:
                #claimName: rap-db-data      
status: {}
    