apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
  namespace: prod
type: Opaque
data:
  azurestorageaccountname: YXF1YWFz
  azurestorageaccountkey: OsfvObgLgU04WwbXo8FBXoirDhA7onGKJfn05A0Tx7Fz7dwpwhHwdcTmqJdhkq/eIQrnJ3NP31hBY0Oy8jULYg==
