apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-job
  namespace: student-prototypes
spec:
  schedule: "* * * * *" # at minute 0 (i.e. every hour)
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cleanup-job-service-account
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:latest
            # The following cmd will delete all pods in the namespace 'student-prototypes' that have an age >= 1 day.
            # It uses the 5th column of the 'kubectl get pod' output
            command: ["sh", "-c", "kubectl delete pod $(kubectl get pod | awk 'match($5,/[0-9]+d/) {print $1}') -n student-prototypes"]
          restartPolicy: Never